version: '2.1'

services:
  app:
    build: .
    volumes:
      - ./:/go/src/github.com/shrinkUrl
    depends_on:
      - redis
    links:
      - redis
    environment:
      US_APP_PORT: 3000
      US_REDIS_HOST: redis:6379
    ports:
      - "3000:3000"

  redis:
    image: redis:3.2
    restart: always
    volumes:
      - ./redis/healthcheck.sh:/healthcheck.sh
    healthcheck:
      test: ['CMD', '/healthcheck.sh']
      interval: 1m
      timeout: 5s
      retries: 3
    expose:
      - '6379'
    command: redis-server --appendonly yes
